[general]
# We use a thin space as seperator
separator = "\u2009"
default_icon = ""
wm_property = "class"

[options]
remove_duplicates = true
no_icon_names = true

[icons]
# Quick access: https://www.nerdfonts.com/cheat-sheet
discord = "\ufb6e"
whatsdesk = "\ufaa2"
firefox = "\ue745"
chromium = "\ue743"
urxvt = "\ue795"
pinentry = "\uf74f"
vscodium = "\ue70c"
teams = "\uf871"
zathura = "\uf725"

[aliases]
"^gimp-" = "gimp"
"^microsoft teams" = "teams"
"^pinentry" = "pinentry"
"zathura$" = "zathura"
