[general]
# We use a thin space as seperator
separator = "\u2009"
default_icon = ""

[options]
remove_duplicates = true
use_instance = true
no_names = true

[icons]
# Quick access: https://www.nerdfonts.com/cheat-sheet
discord = "\ufb6e"
firefox = "\ue745"
urxvt = "\ue795"
"pinentry-gtk-2" = "\uf74f"
vscodium = "\ue70c"
"microsoft teams - preview" = "\uf871"
"org.pwmt.zathura" = "\uf725"

[aliases]
"gimp-2.10" = "gimp"
"microsoft teams - preview" = "teams"
"pinentry-gtk-2" = "pinentry"
